### ISSUE TITLE
Stromer state and position entries no longer work and new entries for statistics etc. are missing

### ISSUE THREAD

**Issue by evoludolab** [elnkosc/stromer_api#1]
First off, thanks for a wonderful piece of software that takes playing with our favourite two-wheel-gadget to an entirely new level! 😄 

Today I was playing around with version 1.0 of your `stromer_api`, when I noticed that you just released an update to 1.1. Unfortunately I get some strange differences between the two versions:

On 1.0 I get (with some anonymizations):
```
>>> print(mybike.__dict__)
{'_StromerBike__session': <requests.sessions.Session object at 0x1022ca8b0>, 
'_StromerBike__state': <stromer_api.BikeState object at 0x1034a3f40>, 
'_StromerBike__position': <stromer_api.BikePosition object at 0x103484550>, 
'_StromerBike__access_token': 'XXX', 
'_StromerBike__bike': 
{'nickname': 'XXX', 'bikeid': XXX, 'bikemodel': 'ST1 X', 'biketype': 'ST2-i', 
'color': 'ocean', 'size': 'sport 22', 
'hardware': 'omniinterfacec', 'connectivity': 'standard', 'has_crash_detection': True, 
'maintenance_feature': 
{'display_maintenance_event': False, 'next_maintenance_km': XXX, 
'next_maintenance_date': 'XXX', 'next_maintenance_interval': 3000, 
'customer_enabled_maintenance': True, 'last_maintenance_reset_km': XXX, 
'last_maintenance_reset_date': 'XXX'}
}
}
```
but with 1.1 I get:
```
>>> print(mybike.__dict__)
{'_StromerBike__session': <requests.sessions.Session object at 0x10d2738b0>, 
'_StromerBike__state': None, 
'_StromerBike__position': None, 
'_StromerBike__statistics': None, 
'_StromerBike__sensors': None, 
'_StromerBike__motor_tuning': None, 
'_StromerBike__settings': None, 
'_StromerBike__user': None, 
'_StromerBike__day_stats': None, 
'_StromerBike__week_stats': None, 
'_StromerBike__month_stats': None, 
'_StromerBike__year_stats': None, 
'_StromerBike__access_token': 'XXX', 
'_StromerBike__bike':
{'nickname': 'XXX', 'bikeid': XXX, 'bikemodel': 'ST1 X', 'biketype': 'ST2-i', 
'color': 'ocean', 'size': 'sport 22', 
'hardware': 'omniinterfacec', 'connectivity': 'standard', 'has_crash_detection': True, 
'maintenance_feature': 
{'display_maintenance_event': False, 'next_maintenance_km': XXX, 
'next_maintenance_date': 'XXX', 'next_maintenance_interval': 3000, 
'customer_enabled_maintenance': True, 'last_maintenance_reset_km': XXX, 
'last_maintenance_reset_date': 'XXX'}
}
}
```
That is, all your interesting new data points on statistics etc. do not seem to be retrieved. Moreover, the previous entries for `_StromerBike__state` and `_StromerBike__position` are now missing.

Maybe I am just doing something silly as a python greenhorn...

**Comment by elnkosc** [comment]
Hi Christophe,
Let me doublecheck this as it looks weird (to say the least). I'm currently
also working on the next version that allows you to set data as well. On
the other hand, knowing __dict__ does not indicate to be a greenhorn ;-)
BR, Koen


Op di 31 jan. 2023 om 04:20 schreef Christoph Hauert <
***@***.***>:

**Comment by elnkosc** [comment]
By the way; when all the data is "None", it means it could not be
retrieved. Are you sure the username, password, and client ID where correct
in the second case also?
BR, Koen

Op di 31 jan. 2023 om 04:20 schreef Christoph Hauert <
***@***.***>:

**Comment by elnkosc** [comment]
Hi Christophe,
Just to be sure; the data is loaded once accessed, so initially all the
items you'll see are None unless you access them.
Please try e.g. print(mybike.state.total_energy_consumption) and then
print(mybike.__dict__) again.
Does this work better?
BR, Koen

Op di 31 jan. 2023 om 04:20 schreef Christoph Hauert <
***@***.***>:

**Comment by evoludolab** [comment]
It seems to me that some caching is going on but I do not fully understand it. I ended up uninstalling all versions of `stromer_api` with `pip` and downloaded the source code. With that setup everything works as expected and I can even play with the source too 😄. 

On first execution `>>> print(mybike.__dict__)` displays the `None` entries but after e.g. executing `>>> print(mybike.position)` the `None` for `'_StromerBike__position'` is replaced with the appropriate object. I was still writing this when your additional response came in - I guess this confirms your suspicion.

Finally, just to confirm, yes the username, password, and client ID were correct.

Can't wait for the version with writing capabilities!
